FROM ghcr.io/mpepping/pandoc:main

COPY assets/ ./assets/
RUN dnf install -y nodejs npm curl && dnf clean all

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY pandoc-service.js ./
RUN mkdir -p /workspace

ENV TEXMFCACHE=/workspace/.texlive

EXPOSE 8080

ENTRYPOINT []
CMD ["node", "pandoc-service.js"]
